project:
  type: website
  output-dir: docs

website:
  title: "Luis Mario Ramirez Cruz"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: about.qmd
      - text: Talks
        href: talks.qmd
      - text: Awards
        href: awards.qmd
      - text: Photos
        href: photos.qmd
      - text: Contact me!
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
