---
title: "Talks"
---

# Oral Presentations

### 2025
**Modeling Habitat Suitability of Alpine Breeding Bird Species in Sierra Nevada, California Based on Historical Data**  
SOAR Annual All-Hands Symposium  
Stanford University

### 2025
**Strategies for Ecological Sustainability in UC Santa Cruz**  
Ecological Society of America 110th Annual Meeting  
Baltimore, MD

### 2025
**3D Reconstruction for Biomass Estimation**  
Banatao Institute Symposium for Drone Education  
UC Santa Cruz

### 2024
**Modeling Habitat Suitability of Alpine Breeding Bird Species in Sierra Nevada, California Based on Historical Data**  
UCSC CAMINO Symposium

---

# Poster Presentations

### 2025
**Comparing the Performance of Statistical vs Mechanistic Models of Range Dynamics of Shortbelly Rockfish in California**  
Western Society of Naturalists (WSN)

### 2025
**Comparing the Performance of Statistical vs Mechanistic Models of Range Dynamics of Shortbelly Rockfish in California**  
SACNAS NDiSTEM Conference

### 2025
**Comparing the Performance of Statistical vs Mechanistic Models of Range Dynamics of Shortbelly Rockfish in California**  
STEM Diversity Symposium
